// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const grass34 = new Entity("Grass")
engine.addEntity(grass34)
const grass34transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
grass34.addComponentOrReplace(grass34transform)
const grass34GLTFShape = new GLTFShape("models2/Grass.glb")
grass34GLTFShape.withCollisions = true
grass34GLTFShape.isPointerBlocker = true
grass34GLTFShape.visible = true
grass34.addComponentOrReplace(grass34GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pond0135 = new Entity("Pond 01")
engine.addEntity(pond0135)
const pond0135transform = new Transform({
  position: new Vector3(6.669325, 0, 9.386615),
  rotation: new Quaternion(0, 0.1799722, 0, -0.9836718),
  scale: new Vector3(1, 1, 1)
})
pond0135.addComponentOrReplace(pond0135transform)
const pond0135GLTFShape = new GLTFShape("models2/Pond_01/Pond_01.glb")
pond0135GLTFShape.withCollisions = true
pond0135GLTFShape.isPointerBlocker = true
pond0135GLTFShape.visible = true
pond0135.addComponentOrReplace(pond0135GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const palmTree0136 = new Entity("Palm Tree 01")
engine.addEntity(palmTree0136)
const palmTree0136transform = new Transform({
  position: new Vector3(8.049986, 0, 12.697),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 0.909521, 1)
})
palmTree0136.addComponentOrReplace(palmTree0136transform)
const palmTree0136GLTFShape = new GLTFShape("models2/PalmTree_01/PalmTree_01.glb")
palmTree0136GLTFShape.withCollisions = true
palmTree0136GLTFShape.isPointerBlocker = true
palmTree0136GLTFShape.visible = true
palmTree0136.addComponentOrReplace(palmTree0136GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const palmTree0137 = new Entity("Palm Tree 01")
engine.addEntity(palmTree0137)
const palmTree0137transform = new Transform({
  position: new Vector3(5.139348, 0, 13.0434),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.63, 0.6072168, 0.72)
})
palmTree0137.addComponentOrReplace(palmTree0137transform)
palmTree0137.addComponentOrReplace(palmTree0136GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const iceCreamTruck0138 = new Entity("Ice Cream Truck 01")
engine.addEntity(iceCreamTruck0138)
const iceCreamTruck0138transform = new Transform({
  position: new Vector3(12.847, 0, 9.031),
  rotation: new Quaternion(0, 0.7181263, 0, 0.6959128),
  scale: new Vector3(1.232953, 1, 1)
})
iceCreamTruck0138.addComponentOrReplace(iceCreamTruck0138transform)
const iceCreamTruck0138GLTFShape = new GLTFShape("models2/IceCreamTruck_01/IceCreamTruck_01.glb")
iceCreamTruck0138GLTFShape.withCollisions = true
iceCreamTruck0138GLTFShape.isPointerBlocker = true
iceCreamTruck0138GLTFShape.visible = true
iceCreamTruck0138.addComponentOrReplace(iceCreamTruck0138GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0439 = new Entity("Fence Wood Medium 04")
engine.addEntity(fenceWoodMedium0439)
const fenceWoodMedium0439transform = new Transform({
  position: new Vector3(15.493, 0, 15.642),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1.11)
})
fenceWoodMedium0439.addComponentOrReplace(fenceWoodMedium0439transform)
const fenceWoodMedium0439GLTFShape = new GLTFShape("models2/FenceWoodMedium_01/FenceWoodMedium_01.glb")
fenceWoodMedium0439GLTFShape.withCollisions = true
fenceWoodMedium0439GLTFShape.isPointerBlocker = true
fenceWoodMedium0439GLTFShape.visible = true
fenceWoodMedium0439.addComponentOrReplace(fenceWoodMedium0439GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const umbrella0140 = new Entity("Umbrella 01")
engine.addEntity(umbrella0140)
const umbrella0140transform = new Transform({
  position: new Vector3(11.648, 0.895, 3.295),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
umbrella0140.addComponentOrReplace(umbrella0140transform)
const umbrella0140GLTFShape = new GLTFShape("models2/Umbrella_01/Umbrella_01.glb")
umbrella0140GLTFShape.withCollisions = true
umbrella0140GLTFShape.isPointerBlocker = true
umbrella0140GLTFShape.visible = true
umbrella0140.addComponentOrReplace(umbrella0140GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const chair0641 = new Entity("Chair 06")
engine.addEntity(chair0641)
const chair0641transform = new Transform({
  position: new Vector3(9.599, 0, 4.416968),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
chair0641.addComponentOrReplace(chair0641transform)
const chair0641GLTFShape = new GLTFShape("models2/Chair_06/Chair_06.glb")
chair0641GLTFShape.withCollisions = true
chair0641GLTFShape.isPointerBlocker = true
chair0641GLTFShape.visible = true
chair0641.addComponentOrReplace(chair0641GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const chair0642 = new Entity("Chair 06")
engine.addEntity(chair0642)
const chair0642transform = new Transform({
  position: new Vector3(9.893, 0, 1.931),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
chair0642.addComponentOrReplace(chair0642transform)
chair0642.addComponentOrReplace(chair0641GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const carpet0243 = new Entity("Carpet 02")
engine.addEntity(carpet0243)
const carpet0243transform = new Transform({
  position: new Vector3(6.841825, 0, 2.755597),
  rotation: new Quaternion(0, 0.1993679, 0, 0.9799247),
  scale: new Vector3(1.3, 1, 1.3)
})
carpet0243.addComponentOrReplace(carpet0243transform)
const carpet0243GLTFShape = new GLTFShape("models2/Carpet_02/Carpet_02.glb")
carpet0243GLTFShape.withCollisions = true
carpet0243GLTFShape.isPointerBlocker = true
carpet0243GLTFShape.visible = true
carpet0243.addComponentOrReplace(carpet0243GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const michiToddRabbitLampsmall44 = new Entity("Michi Todd Rabbit Lamp(Small)")
engine.addEntity(michiToddRabbitLampsmall44)
const michiToddRabbitLampsmall44transform = new Transform({
  position: new Vector3(1.831182, 0, 1.869462),
  rotation: new Quaternion(0, 0.850471, 0, -0.5260221),
  scale: new Vector3(1, 1, 1)
})
michiToddRabbitLampsmall44.addComponentOrReplace(michiToddRabbitLampsmall44transform)
const michiToddRabbitLampsmall44GLTFShape = new GLTFShape("models2/Michi_Todd_Rabbit_Lamp(Small).glb")
michiToddRabbitLampsmall44GLTFShape.withCollisions = true
michiToddRabbitLampsmall44GLTFShape.isPointerBlocker = true
michiToddRabbitLampsmall44GLTFShape.visible = true
michiToddRabbitLampsmall44.addComponentOrReplace(michiToddRabbitLampsmall44GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const bottle0845 = new Entity("Bottle 08")
engine.addEntity(bottle0845)
const bottle0845transform = new Transform({
  position: new Vector3(6.626, 0, 3.646148),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.276, 1, 1.308)
})
bottle0845.addComponentOrReplace(bottle0845transform)
const bottle0845GLTFShape = new GLTFShape("models2/Bottle_08/Bottle_08.glb")
bottle0845GLTFShape.withCollisions = true
bottle0845GLTFShape.isPointerBlocker = true
bottle0845GLTFShape.visible = true
bottle0845.addComponentOrReplace(bottle0845GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const bottle0446 = new Entity("Bottle 04")
engine.addEntity(bottle0446)
const bottle0446transform = new Transform({
  position: new Vector3(6.582, 0, 2.273167),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
bottle0446.addComponentOrReplace(bottle0446transform)
const bottle0446GLTFShape = new GLTFShape("models2/Bottle_04/Bottle_04.glb")
bottle0446GLTFShape.withCollisions = true
bottle0446GLTFShape.isPointerBlocker = true
bottle0446GLTFShape.visible = true
bottle0446.addComponentOrReplace(bottle0446GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0347 = new Entity("Fence Wood Medium 03")
engine.addEntity(fenceWoodMedium0347)
const fenceWoodMedium0347transform = new Transform({
  position: new Vector3(12.295, 0, 15.653),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1.456)
})
fenceWoodMedium0347.addComponentOrReplace(fenceWoodMedium0347transform)
fenceWoodMedium0347.addComponentOrReplace(fenceWoodMedium0439GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0148 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0148)
const fenceWoodMedium0148transform = new Transform({
  position: new Vector3(3.694, 0, 15.598),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1.145112)
})
fenceWoodMedium0148.addComponentOrReplace(fenceWoodMedium0148transform)
fenceWoodMedium0148.addComponentOrReplace(fenceWoodMedium0439GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0249 = new Entity("Fence Wood Medium 02")
engine.addEntity(fenceWoodMedium0249)
const fenceWoodMedium0249transform = new Transform({
  position: new Vector3(7.803, 0, 15.605),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1.379)
})
fenceWoodMedium0249.addComponentOrReplace(fenceWoodMedium0249transform)
fenceWoodMedium0249.addComponentOrReplace(fenceWoodMedium0439GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0150 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0150)
const fenceWoodMedium0150transform = new Transform({
  position: new Vector3(15.5, 0, 15.61143),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1.391)
})
fenceWoodMedium0150.addComponentOrReplace(fenceWoodMedium0150transform)
fenceWoodMedium0150.addComponentOrReplace(fenceWoodMedium0439GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0151 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0151)
const fenceWoodMedium0151transform = new Transform({
  position: new Vector3(15.5, 0, 11.4),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1.386)
})
fenceWoodMedium0151.addComponentOrReplace(fenceWoodMedium0151transform)
fenceWoodMedium0151.addComponentOrReplace(fenceWoodMedium0439GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0152 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0152)
const fenceWoodMedium0152transform = new Transform({
  position: new Vector3(15.5, 0, 7.149),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1.225)
})
fenceWoodMedium0152.addComponentOrReplace(fenceWoodMedium0152transform)
fenceWoodMedium0152.addComponentOrReplace(fenceWoodMedium0439GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0153 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0153)
const fenceWoodMedium0153transform = new Transform({
  position: new Vector3(15.5, 0, 3.377),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 0.9296545)
})
fenceWoodMedium0153.addComponentOrReplace(fenceWoodMedium0153transform)
fenceWoodMedium0153.addComponentOrReplace(fenceWoodMedium0439GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const table0354 = new Entity("Table 03")
engine.addEntity(table0354)
const table0354transform = new Transform({
  position: new Vector3(11.695, 0, 3.309),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
table0354.addComponentOrReplace(table0354transform)
const table0354GLTFShape = new GLTFShape("models2/Table_03/Table_03.glb")
table0354GLTFShape.withCollisions = true
table0354GLTFShape.isPointerBlocker = true
table0354GLTFShape.visible = true
table0354.addComponentOrReplace(table0354GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
}

