// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const grass34 = new Entity("Grass")
engine.addEntity(grass34)
const grass34transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
grass34.addComponentOrReplace(grass34transform)
const grass34GLTFShape = new GLTFShape("models2/Grass.glb")
grass34GLTFShape.withCollisions = true
grass34GLTFShape.isPointerBlocker = true
grass34GLTFShape.visible = true
grass34.addComponentOrReplace(grass34GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pond0135 = new Entity("Pond 01")
engine.addEntity(pond0135)
const pond0135transform = new Transform({
  position: new Vector3(6.669325, 0, 9.386615),
  rotation: new Quaternion(0, 0.1799722, 0, -0.9836718),
  scale: new Vector3(1, 1, 1)
})
pond0135.addComponentOrReplace(pond0135transform)
const pond0135GLTFShape = new GLTFShape("models2/Pond_01/Pond_01.glb")
pond0135GLTFShape.withCollisions = true
pond0135GLTFShape.isPointerBlocker = true
pond0135GLTFShape.visible = true
pond0135.addComponentOrReplace(pond0135GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const palmTree0136 = new Entity("Palm Tree 01")
engine.addEntity(palmTree0136)
const palmTree0136transform = new Transform({
  position: new Vector3(8.049986, 0, 12.697),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 0.909521, 1)
})
palmTree0136.addComponentOrReplace(palmTree0136transform)
const palmTree0136GLTFShape = new GLTFShape("models2/PalmTree_01/PalmTree_01.glb")
palmTree0136GLTFShape.withCollisions = true
palmTree0136GLTFShape.isPointerBlocker = true
palmTree0136GLTFShape.visible = true
palmTree0136.addComponentOrReplace(palmTree0136GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const palmTree0137 = new Entity("Palm Tree 01")
engine.addEntity(palmTree0137)
const palmTree0137transform = new Transform({
  position: new Vector3(5.139348, 0, 13.0434),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.63, 0.6072168, 0.72)
})
palmTree0137.addComponentOrReplace(palmTree0137transform)
palmTree0137.addComponentOrReplace(palmTree0136GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0439 = new Entity("Fence Wood Medium 04")
engine.addEntity(fenceWoodMedium0439)
const fenceWoodMedium0439transform = new Transform({
  position: new Vector3(15.493, 0, 15.642),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 5.113576)
})
fenceWoodMedium0439.addComponentOrReplace(fenceWoodMedium0439transform)
const fenceWoodMedium0439GLTFShape = new GLTFShape("models2/FenceWoodMedium_01/FenceWoodMedium_01.glb")
fenceWoodMedium0439GLTFShape.withCollisions = true
fenceWoodMedium0439GLTFShape.isPointerBlocker = true
fenceWoodMedium0439GLTFShape.visible = true
fenceWoodMedium0439.addComponentOrReplace(fenceWoodMedium0439GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const umbrella0140 = new Entity("Umbrella 01")
engine.addEntity(umbrella0140)
const umbrella0140transform = new Transform({
  position: new Vector3(10.316, 0.177, 3.145),
  rotation: new Quaternion(0, 0, 0.2512249, -0.9679288),
  scale: new Vector3(1, 1.25, 1)
})
umbrella0140.addComponentOrReplace(umbrella0140transform)
const umbrella0140GLTFShape = new GLTFShape("models2/Umbrella_01/Umbrella_01.glb")
umbrella0140GLTFShape.withCollisions = true
umbrella0140GLTFShape.isPointerBlocker = true
umbrella0140GLTFShape.visible = true
umbrella0140.addComponentOrReplace(umbrella0140GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const chair0641 = new Entity("Chair 06")
engine.addEntity(chair0641)
const chair0641transform = new Transform({
  position: new Vector3(9.599, 0, 4.416968),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
chair0641.addComponentOrReplace(chair0641transform)
const chair0641GLTFShape = new GLTFShape("models2/Chair_06/Chair_06.glb")
chair0641GLTFShape.withCollisions = true
chair0641GLTFShape.isPointerBlocker = true
chair0641GLTFShape.visible = true
chair0641.addComponentOrReplace(chair0641GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const chair0642 = new Entity("Chair 06")
engine.addEntity(chair0642)
const chair0642transform = new Transform({
  position: new Vector3(9.893, 0, 1.931),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
chair0642.addComponentOrReplace(chair0642transform)
chair0642.addComponentOrReplace(chair0641GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const carpet0243 = new Entity("Carpet 02")
engine.addEntity(carpet0243)
const carpet0243transform = new Transform({
  position: new Vector3(6.841825, 0, 2.755597),
  rotation: new Quaternion(0, 0.1993679, 0, 0.9799247),
  scale: new Vector3(1.3, 1, 1.3)
})
carpet0243.addComponentOrReplace(carpet0243transform)
const carpet0243GLTFShape = new GLTFShape("models2/Carpet_02/Carpet_02.glb")
carpet0243GLTFShape.withCollisions = true
carpet0243GLTFShape.isPointerBlocker = true
carpet0243GLTFShape.visible = true
carpet0243.addComponentOrReplace(carpet0243GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0150 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0150)
const fenceWoodMedium0150transform = new Transform({
  position: new Vector3(15.5, 0, 15.61143),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 5.119618)
})
fenceWoodMedium0150.addComponentOrReplace(fenceWoodMedium0150transform)
fenceWoodMedium0150.addComponentOrReplace(fenceWoodMedium0439GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0161 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0161)
const fenceWoodMedium0161transform = new Transform({
  position: new Vector3(15.336, 0, 0.148),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 4.987464)
})
fenceWoodMedium0161.addComponentOrReplace(fenceWoodMedium0161transform)
fenceWoodMedium0161.addComponentOrReplace(fenceWoodMedium0439GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
}

