// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBase3 = new Entity("Floor Base")
engine.addEntity(floorBase3)
const floorBase3transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBase3.addComponentOrReplace(floorBase3transform)
const floorBase3GLTFShape = new GLTFShape("models/FloorBaseConcrete_01/FloorBaseConcrete_01.glb")
floorBase3GLTFShape.withCollisions = true
floorBase3GLTFShape.isPointerBlocker = true
floorBase3GLTFShape.visible = true
floorBase3.addComponentOrReplace(floorBase3GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const plainGlassWall24 = new Entity("Plain Glass Wall2")
engine.addEntity(plainGlassWall24)
const plainGlassWall24transform = new Transform({
  position: new Vector3(16, 0, 0.3332334),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(8, 1.5, 1)
})
plainGlassWall24.addComponentOrReplace(plainGlassWall24transform)
const plainGlassWall24GLTFShape = new GLTFShape("models/PlainGlassWall.glb")
plainGlassWall24GLTFShape.withCollisions = true
plainGlassWall24GLTFShape.isPointerBlocker = true
plainGlassWall24GLTFShape.visible = true
plainGlassWall24.addComponentOrReplace(plainGlassWall24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const plainGlassWall7 = new Entity("Plain Glass Wall")
engine.addEntity(plainGlassWall7)
const plainGlassWall7transform = new Transform({
  position: new Vector3(0.1291967, 8.497621, 0.04499979),
  rotation: new Quaternion(0.5034785, 0.4964971, -0.5034785, 0.4964972),
  scale: new Vector3(7.8, 2.754997, 0.22)
})
plainGlassWall7.addComponentOrReplace(plainGlassWall7transform)
plainGlassWall7.addComponentOrReplace(plainGlassWall24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const whiteModernArmchair10 = new Entity("White Modern Armchair")
engine.addEntity(whiteModernArmchair10)
const whiteModernArmchair10transform = new Transform({
  position: new Vector3(4.451511, 0.053, 2.270279),
  rotation: new Quaternion(0, -0.02606289, 0, -0.9996604),
  scale: new Vector3(1, 1, 1)
})
whiteModernArmchair10.addComponentOrReplace(whiteModernArmchair10transform)
const whiteModernArmchair10GLTFShape = new GLTFShape("models/WhiteModernArmchair.glb")
whiteModernArmchair10GLTFShape.withCollisions = true
whiteModernArmchair10GLTFShape.isPointerBlocker = true
whiteModernArmchair10GLTFShape.visible = true
whiteModernArmchair10.addComponentOrReplace(whiteModernArmchair10GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const tableWithChairs14 = new Entity("Table with Chairs")
engine.addEntity(tableWithChairs14)
const tableWithChairs14transform = new Transform({
  position: new Vector3(10.613, 0, 9.435321),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
tableWithChairs14.addComponentOrReplace(tableWithChairs14transform)
const tableWithChairs14GLTFShape = new GLTFShape("models/Table_with_Chairs.glb")
tableWithChairs14GLTFShape.withCollisions = true
tableWithChairs14GLTFShape.isPointerBlocker = true
tableWithChairs14GLTFShape.visible = true
tableWithChairs14.addComponentOrReplace(tableWithChairs14GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const tableWithChairs15 = new Entity("Table with Chairs")
engine.addEntity(tableWithChairs15)
const tableWithChairs15transform = new Transform({
  position: new Vector3(5.739843, 0, 11.21289),
  rotation: new Quaternion(0, 0.1322564, 0, -0.9912155),
  scale: new Vector3(1, 1, 1)
})
tableWithChairs15.addComponentOrReplace(tableWithChairs15transform)
tableWithChairs15.addComponentOrReplace(tableWithChairs14GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const table0416 = new Entity("Table 04")
engine.addEntity(table0416)
const table0416transform = new Transform({
  position: new Vector3(5.302524, 0, 3.436015),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
table0416.addComponentOrReplace(table0416transform)
const table0416GLTFShape = new GLTFShape("models/Table_04/Table_04.glb")
table0416GLTFShape.withCollisions = true
table0416GLTFShape.isPointerBlocker = true
table0416GLTFShape.visible = true
table0416.addComponentOrReplace(table0416GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const whiteModernArmchair17 = new Entity("White Modern Armchair")
engine.addEntity(whiteModernArmchair17)
const whiteModernArmchair17transform = new Transform({
  position: new Vector3(7.238334, 0, 3.127306),
  rotation: new Quaternion(0, 0.3773853, 0, -0.9260564),
  scale: new Vector3(1, 1, 1)
})
whiteModernArmchair17.addComponentOrReplace(whiteModernArmchair17transform)
whiteModernArmchair17.addComponentOrReplace(whiteModernArmchair10GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore0118 = new Entity("Tree Sycamore 01")
engine.addEntity(treeSycamore0118)
const treeSycamore0118transform = new Transform({
  position: new Vector3(11.765, 0, 3.326),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
treeSycamore0118.addComponentOrReplace(treeSycamore0118transform)
const treeSycamore0118GLTFShape = new GLTFShape("models/TreeSycamore_01/TreeSycamore_01.glb")
treeSycamore0118GLTFShape.withCollisions = true
treeSycamore0118GLTFShape.isPointerBlocker = true
treeSycamore0118GLTFShape.visible = true
treeSycamore0118.addComponentOrReplace(treeSycamore0118GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const bush0119 = new Entity("Bush 01")
engine.addEntity(bush0119)
const bush0119transform = new Transform({
  position: new Vector3(12.521, 0, 3.740001),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
bush0119.addComponentOrReplace(bush0119transform)
const bush0119GLTFShape = new GLTFShape("models/Bush_01/Bush_01.glb")
bush0119GLTFShape.withCollisions = true
bush0119GLTFShape.isPointerBlocker = true
bush0119GLTFShape.visible = true
bush0119.addComponentOrReplace(bush0119GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const grass0220 = new Entity("Grass 02")
engine.addEntity(grass0220)
const grass0220transform = new Transform({
  position: new Vector3(10.997, 0, 3.615),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
grass0220.addComponentOrReplace(grass0220transform)
const grass0220GLTFShape = new GLTFShape("models/Grass_02/Grass_02.glb")
grass0220GLTFShape.withCollisions = true
grass0220GLTFShape.isPointerBlocker = true
grass0220GLTFShape.visible = true
grass0220.addComponentOrReplace(grass0220GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const plant0621 = new Entity("Plant 06")
engine.addEntity(plant0621)
const plant0621transform = new Transform({
  position: new Vector3(10.419, 0.661, 4.478),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
plant0621.addComponentOrReplace(plant0621transform)
const plant0621GLTFShape = new GLTFShape("models/Plant_06/Plant_06.glb")
plant0621GLTFShape.withCollisions = true
plant0621GLTFShape.isPointerBlocker = true
plant0621GLTFShape.visible = true
plant0621.addComponentOrReplace(plant0621GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fencePicketWhiteLarge0122 = new Entity("Fence Picket White Large 01")
engine.addEntity(fencePicketWhiteLarge0122)
const fencePicketWhiteLarge0122transform = new Transform({
  position: new Vector3(15.316, 0, 15.864),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
fencePicketWhiteLarge0122.addComponentOrReplace(fencePicketWhiteLarge0122transform)
const fencePicketWhiteLarge0122GLTFShape = new GLTFShape("models/FencePicketWhiteLarge_01/FencePicketWhiteLarge_01.glb")
fencePicketWhiteLarge0122GLTFShape.withCollisions = true
fencePicketWhiteLarge0122GLTFShape.isPointerBlocker = true
fencePicketWhiteLarge0122GLTFShape.visible = true
fencePicketWhiteLarge0122.addComponentOrReplace(fencePicketWhiteLarge0122GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fencePicketWhiteLarge0123 = new Entity("Fence Picket White Large 01")
engine.addEntity(fencePicketWhiteLarge0123)
const fencePicketWhiteLarge0123transform = new Transform({
  position: new Vector3(15.398, 0, 10.851),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
fencePicketWhiteLarge0123.addComponentOrReplace(fencePicketWhiteLarge0123transform)
fencePicketWhiteLarge0123.addComponentOrReplace(fencePicketWhiteLarge0122GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fencePicketWhiteLarge0124 = new Entity("Fence Picket White Large 01")
engine.addEntity(fencePicketWhiteLarge0124)
const fencePicketWhiteLarge0124transform = new Transform({
  position: new Vector3(15.351, 0, 5.635),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
fencePicketWhiteLarge0124.addComponentOrReplace(fencePicketWhiteLarge0124transform)
fencePicketWhiteLarge0124.addComponentOrReplace(fencePicketWhiteLarge0122GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const grass0225 = new Entity("Grass 02")
engine.addEntity(grass0225)
const grass0225transform = new Transform({
  position: new Vector3(15.599, 0, 11.385),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.653, 7.232, 3.378)
})
grass0225.addComponentOrReplace(grass0225transform)
grass0225.addComponentOrReplace(grass0220GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const plant0726 = new Entity("Plant 07")
engine.addEntity(plant0726)
const plant0726transform = new Transform({
  position: new Vector3(15.657, 0, 12.255),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.61, 2.256, 1.571)
})
plant0726.addComponentOrReplace(plant0726transform)
const plant0726GLTFShape = new GLTFShape("models/Plant_07/Plant_07.glb")
plant0726GLTFShape.withCollisions = true
plant0726GLTFShape.isPointerBlocker = true
plant0726GLTFShape.visible = true
plant0726.addComponentOrReplace(plant0726GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const grass0227 = new Entity("Grass 02")
engine.addEntity(grass0227)
const grass0227transform = new Transform({
  position: new Vector3(15.657, 0, 5.879),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.434026, 5.271, 1.458)
})
grass0227.addComponentOrReplace(grass0227transform)
grass0227.addComponentOrReplace(grass0220GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const plant0728 = new Entity("Plant 07")
engine.addEntity(plant0728)
const plant0728transform = new Transform({
  position: new Vector3(15.733, 0, 6.549),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 2.761, 2.809)
})
plant0728.addComponentOrReplace(plant0728transform)
plant0728.addComponentOrReplace(plant0726GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const barBlack29 = new Entity("Bar Black")
engine.addEntity(barBlack29)
const barBlack29transform = new Transform({
  position: new Vector3(3.256779, 0, 14.51734),
  rotation: new Quaternion(0, 0.9999905, 0, -0.004363329),
  scale: new Vector3(1.609411, 1.406, 0.821)
})
barBlack29.addComponentOrReplace(barBlack29transform)
const barBlack29GLTFShape = new GLTFShape("models/Bar_Black.glb")
barBlack29GLTFShape.withCollisions = true
barBlack29GLTFShape.isPointerBlocker = true
barBlack29GLTFShape.visible = true
barBlack29.addComponentOrReplace(barBlack29GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const umbrella0231 = new Entity("Umbrella 02")
engine.addEntity(umbrella0231)
const umbrella0231transform = new Transform({
  position: new Vector3(5.74492, 0.5870104, 11.33167),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
umbrella0231.addComponentOrReplace(umbrella0231transform)
const umbrella0231GLTFShape = new GLTFShape("models/Umbrella_02/Umbrella_02.glb")
umbrella0231GLTFShape.withCollisions = true
umbrella0231GLTFShape.isPointerBlocker = true
umbrella0231GLTFShape.visible = true
umbrella0231.addComponentOrReplace(umbrella0231GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
  floorBase:{
    entity: floorBase3,
    transform: floorBase3transform,
    GLTFShape: floorBase3GLTFShape,
  },
  plainGlassWall2:{
    entity: plainGlassWall24,
    transform: plainGlassWall24transform,
    GLTFShape: plainGlassWall24GLTFShape,
  },
  plainGlassWall:{
    entity: plainGlassWall7,
    transform: plainGlassWall7transform,
    GLTFShape: plainGlassWall24GLTFShape,
  },
}

